### ISSUE TITLE
About Code for Figure Two (Boxplots for DSC on demographics including ages, institute, ages, etc..)

### ISSUE THREAD

**Issue by ChunTungZhuangLeo** [MrGiovanni/Touchstone#1]
Hi, may I have the code for figure 2? The one titled as "Potential confounders significantly impact AI performance"
![fig2](https://github.com/MrGiovanni/Touchstone/assets/143352122/826525d4-177e-4744-8b3a-7a14e085e9ec)

**Comment by PedroRASB** [comment]
Hi, thank you for your question. 

You can find this code in plot/AggregatedBoxplot.py. We have updated our readme to better explain how to run it. Please consider that the plots for the JHH dataset (green) will be left blank, because this data is private. However, the code will produce all TotalSegmentator and DAP Atlas plots (orange and blue).
